---
# defaults file for satellite-server
satellite_server_pre_pkgs:
  - chrony
  - sos

satellite_server_fw_ports:
  - 53/udp
  - 53/tcp
  - 67/udp
  - 69/udp
  - 80/tcp
  - 443/tcp
  - 5647/tcp
  - 8000/tcp
  - 9090/tcp
  - 8140/tcp
  - 8443/tcp

satellite_server_installer_scenario: satellite
