- name: Instalando y configurando Capsule
  hosts: SATELLITE_CAPSULE_ENP
  become: true
  pre_tasks:
    - name: Validando requerimientos de hardware del servidor Red Hat Satellite Capsule.
      ansible.builtin.fail:
        msg: |
          El servidor {{ inventory_hostname }} NO cumple los requerimientos minimos para instalar Red Hat Satellite Capsule.
          Por favor establezca los requerimientos minimos y vuelva a ejecutar la instalacion.
      when: 
        - ansible_facts['processor_vcpus'] < 4 or
          ansible_facts['memtotal_mb'] < 19773
      
    - name: Validando registro DNS del servidor Red Hat Satellite Capsule.
      ansible.builtin.fail:
        msg: |
          El servidor {{ inventory_hostname }} NO resuelve por DNS valido.
          Por favor compruebe el servidor DNS establecido en el servidor Red Hat Satellite Capsule.
      when:
        - lookup('community.general.dig', ansible_facts['fqdn']) != ansible_facts['default_ipv4']['address']

  roles:
    - role: satellite-capsule
    - role: satellite-capsule-configuration    
